# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: fedora-cosmic-atomic
description: My personal OS image based on official Fedora COSMIC.

base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 42

platforms:
  - linux/amd64/v2

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      # These must be under 'add' if you are using 'dnf' module
      add:
        - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - ffmpeg-libs
        - libavcodec-freeworld
        - mesa-va-drivers-freeworld
        - mesa-vdpau-drivers-freeworld
        - libva-utils

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
      - scope: user

  - type: signing
